package bd.database;

import com.google.common.base.CaseFormat;

import bd.block.*;
import bd.item.*;
import cpw.mods.fml.common.registry.GameRegistry;
import lotr.common.LOTRCreativeTabs;
import lotr.common.item.*;
import lotr.common.item.LOTRItemDagger.DaggerEffect;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.potion.Potion;

public class BDRegistry {

	public static Block table_eregion;
	public static Block table_khand;
	public static Item ametamy;
	public static Item amogus;
	public static Item apple_cookies;
	public static Item armorcoin1;
	public static Item armorcoin2;
	public static Item armorcoin3;
	public static Item arrow_blindness;
	public static Item arrow_fire;
	public static Item arrow_hunger;
	public static Item arrow_slowness;
	public static Item bbky1;
	public static Item bbky2;
	public static Item bblis1;
	public static Item bblis2;
	public static Item bblis3;
	public static Item berry_cookies;
	public static Item blackbag;
	public static Item bluebag;
	public static Item bottle1;
	public static Item bottle2;
	public static Item bottle3;
	public static Item chocolate_cookies;
	public static Item coin_dwarf;
	public static Item coin_enedwaith;
	public static Item coin_eregion;
	public static Item coin_eriador;
	public static Item coin_harad;
	public static Item coin_karndum;
	public static Item coin_khand;
	public static Item coin_mordor;
	public static Item coin_nandor;
	public static Item coin_noldor;
	public static Item coin_north;
	public static Item coin_numenor;
	public static Item coin_red_mountains;
	public static Item coin_rhovanion;
	public static Item coin_rhun;
	public static Item coin_sindar;
	public static Item crossbow_bolt_blindness;
	public static Item crossbow_bolt_fire;
	public static Item crossbow_bolt_hunger;
	public static Item crossbow_bolt_slowness;
	public static Item crown;
	public static Item dark_boots;
	public static Item dark_bow;
	public static Item dark_chestplate;
	public static Item dark_crossbow;
	public static Item dark_helmet;
	public static Item dark_leggings;
	public static Item dark_spear;
	public static Item dark_sword;
	public static Item darkgrove_boots;
	public static Item darkgrove_bow;
	public static Item darkgrove_chestplate;
	public static Item darkgrove_helmet;
	public static Item darkgrove_leggings;
	public static Item darkgrove_pike;
	public static Item darkgrove_sword;
	public static Item dess;
	public static Item enedwaith1_bow;
	public static Item enedwaith1_crossbow;
	public static Item enedwaith1_pike;
	public static Item enedwaith1_spear;
	public static Item enedwaith1_sword;
	public static Item enedwaith2_boots;
	public static Item enedwaith2_bow;
	public static Item enedwaith2_chestplate;
	public static Item enedwaith2_crossbow;
	public static Item enedwaith2_hammer;
	public static Item enedwaith2_helmet;
	public static Item enedwaith2_leggings;
	public static Item enedwaith2_pike;
	public static Item enedwaith2_spear;
	public static Item enedwaith2_sword;
	public static Item enedwaith3_boots;
	public static Item enedwaith3_chestplate;
	public static Item enedwaith3_helmet;
	public static Item enedwaith3_leggings;
	public static Item enedwaithy_hammer;
	public static Item eregion1_boots;
	public static Item eregion1_bow;
	public static Item eregion1_chestplate;
	public static Item eregion1_dagger;
	public static Item eregion1_dagger_poisoned;
	public static Item eregion1_helmet;
	public static Item eregion1_leggings;
	public static Item eregion1_pike;
	public static Item eregion1_polearm;
	public static Item eregion1_spear;
	public static Item eregion1_sword;
	public static Item eregion2_boots;
	public static Item eregion2_bow;
	public static Item eregion2_chestplate;
	public static Item eregion2_dagger;
	public static Item eregion2_dagger_poisoned;
	public static Item eregion2_helmet;
	public static Item eregion2_leggings;
	public static Item eregion2_pike;
	public static Item eregion2_polearm;
	public static Item eregion2_spear;
	public static Item eregion2_sword;
	public static Item eregion3_boots;
	public static Item eregion3_chestplate;
	public static Item eregion3_helmet;
	public static Item eregion3_leggings;
	public static Item eregiony_polearm;
	public static Item eriador1_boots;
	public static Item eriador1_bow;
	public static Item eriador1_chestplate;
	public static Item eriador1_dagger;
	public static Item eriador1_dagger_poisoned;
	public static Item eriador1_hammer;
	public static Item eriador1_helmet;
	public static Item eriador1_leggings;
	public static Item eriador1_pike;
	public static Item eriador1_spear;
	public static Item eriador1_sword;
	public static Item eriador2_boots;
	public static Item eriador2_bow;
	public static Item eriador2_chestplate;
	public static Item eriador2_dagger;
	public static Item eriador2_dagger_poisoned;
	public static Item eriador2_hammer;
	public static Item eriador2_helmet;
	public static Item eriador2_leggings;
	public static Item eriador2_pike;
	public static Item eriador2_spear;
	public static Item eriador2_sword;
	public static Item eriador3_boots;
	public static Item eriador3_chestplate;
	public static Item eriador3_helmet;
	public static Item eriador3_leggings;
	public static Item eriadory_hammer;
	public static Item fish_arapaima;
	public static Item fish_atlantic_cod;
	public static Item fish_atlantic_halibut;
	public static Item fish_atlantic_herring;
	public static Item fish_bayad;
	public static Item fish_blackfish;
	public static Item fish_bluegill;
	public static Item fish_boulti;
	public static Item fish_brown_shrooma;
	public static Item fish_brown_trout;
	public static Item fish_capitaine;
	public static Item fish_carp;
	public static Item fish_catfish;
	public static Item fish_fish_bones;
	public static Item fish_goldfish;
	public static Item fish_minnow;
	public static Item fish_muskellunge;
	public static Item fish_pacific_halibut;
	public static Item fish_perch;
	public static Item fish_pink_salmon;
	public static Item fish_piranha;
	public static Item fish_pollock;
	public static Item fish_rainbow_trout;
	public static Item fish_red_grouper;
	public static Item fish_red_shrooma;
	public static Item fish_smallmouth_bass;
	public static Item fish_synodontis;
	public static Item fish_tambaqui;
	public static Item fish_tuna;
	public static Item fkris;
	public static Item fstone;
	public static Item goldamy;
	public static Item grapefruit;
	public static Item guardian_boots;
	public static Item guardian_chestplate;
	public static Item guardian_crossbow;
	public static Item guardian_dagger_poisoned;
	public static Item guardian_helmet;
	public static Item guardian_leggings;
	public static Item guardian_spear;
	public static Item harad2_boots;
	public static Item harad2_bow;
	public static Item harad2_chestplate;
	public static Item harad2_dagger;
	public static Item harad2_dagger_poisoned;
	public static Item harad2_hammer;
	public static Item harad2_helmet;
	public static Item harad2_leggings;
	public static Item harad2_pike;
	public static Item harad2_spear;
	public static Item harad2_sword;
	public static Item harad3_boots;
	public static Item harad3_chestplate;
	public static Item harad3_helmet;
	public static Item harad3_leggings;
	public static Item harady_dagger_poisoned;
	public static Item heal1;
	public static Item heal2;
	public static Item heal3;
	public static Item honey_cookies;
	public static Item hors;
	public static Item irkey;
	public static Item irlock;
	public static Item jabroni;
	public static Item karndum1_bow;
	public static Item karndum1_pike;
	public static Item karndum2_battleaxe;
	public static Item karndum2_boots;
	public static Item karndum2_bow;
	public static Item karndum2_chestplate;
	public static Item karndum2_dagger;
	public static Item karndum2_dagger_poisoned;
	public static Item karndum2_hammer;
	public static Item karndum2_helmet;
	public static Item karndum2_leggings;
	public static Item karndum2_pike;
	public static Item karndum2_spear;
	public static Item karndum2_sword;
	public static Item karndum3_boots;
	public static Item karndum3_chestplate;
	public static Item karndum3_helmet;
	public static Item karndum3_leggings;
	public static Item karndumy_sword;
	public static Item khand1_boots;
	public static Item khand1_bow;
	public static Item khand1_chestplate;
	public static Item khand1_dagger;
	public static Item khand1_dagger_poisoned;
	public static Item khand1_hammer;
	public static Item khand1_leggings;
	public static Item khand1_pike;
	public static Item khand1_spear;
	public static Item khand1_sword;
	public static Item khand2_boots;
	public static Item khand2_bow;
	public static Item khand2_chestplate;
	public static Item khand2_dagger;
	public static Item khand2_dagger_poisoned;
	public static Item khand2_hammer;
	public static Item khand2_helmet;
	public static Item khand2_leggings;
	public static Item khand2_pike;
	public static Item khand2_spear;
	public static Item khand2_sword;
	public static Item khand3_boots;
	public static Item khand3_chestplate;
	public static Item khand3_leggings;
	public static Item khandy_bow;
	public static Item khazad1_crossbow;
	public static Item khazad2_battleaxe;
	public static Item khazad2_boots;
	public static Item khazad2_chestplate;
	public static Item khazad2_crossbow;
	public static Item khazad2_dagger;
	public static Item khazad2_dagger_poisoned;
	public static Item khazad2_hammer;
	public static Item khazad2_helmet;
	public static Item khazad2_leggings;
	public static Item khazad2_pike;
	public static Item khazad2_spear;
	public static Item khazad2_sword;
	public static Item khazad3_boots;
	public static Item khazad3_chestplate;
	public static Item khazad3_helmet;
	public static Item khazad3_leggings;
	public static Item khazady_crossbow;
	public static Item kiwi;
	public static Item krest;
	public static Item kris;
	public static Item light_boots;
	public static Item light_bow;
	public static Item light_chestplate;
	public static Item light_crossbow;
	public static Item light_helmet;
	public static Item light_leggings;
	public static Item light_spear;
	public static Item light_sword;
	public static Item manykey;
	public static Item maple_leaf;
	public static Item milk_cookies;
	public static Item mirror;
	public static Item mordor2_boots;
	public static Item mordor2_chestplate;
	public static Item mordor2_helmet;
	public static Item mordor2_leggings;
	public static Item mordor2_polearm;
	public static Item mordory_spear;
	public static Item mug_maple;
	public static Item nandor1_pike;
	public static Item nandor2_boots;
	public static Item nandor2_bow;
	public static Item nandor2_chestplate;
	public static Item nandor2_dagger;
	public static Item nandor2_dagger_poisoned;
	public static Item nandor2_helmet;
	public static Item nandor2_leggings;
	public static Item nandor2_pike;
	public static Item nandor2_polearm;
	public static Item nandor2_spear;
	public static Item nandor2_sword;
	public static Item nandor3_boots;
	public static Item nandor3_chestplate;
	public static Item nandor3_helmet;
	public static Item nandor3_leggings;
	public static Item nandory_bow;
	public static Item noldor1_pike;
	public static Item noldor2_boots;
	public static Item noldor2_bow;
	public static Item noldor2_chestplate;
	public static Item noldor2_dagger;
	public static Item noldor2_dagger_poisoned;
	public static Item noldor2_helmet;
	public static Item noldor2_leggings;
	public static Item noldor2_pike;
	public static Item noldor2_polearm;
	public static Item noldor2_spear;
	public static Item noldor2_sword;
	public static Item noldor3_boots;
	public static Item noldor3_chestplate;
	public static Item noldor3_helmet;
	public static Item noldor3_leggings;
	public static Item noldory_sword;
	public static Item north2_boots;
	public static Item north2_bow;
	public static Item north2_chestplate;
	public static Item north2_dagger;
	public static Item north2_dagger_poisoned;
	public static Item north2_hammer;
	public static Item north2_helmet;
	public static Item north2_leggings;
	public static Item north2_pike;
	public static Item north2_spear;
	public static Item north2_sword;
	public static Item north3_boots;
	public static Item north3_chestplate;
	public static Item north3_helmet;
	public static Item north3_leggings;
	public static Item northy_sword;
	public static Item numenor1_battleaxe;
	public static Item numenor1_crossbow;
	public static Item numenor2_battleaxe;
	public static Item numenor2_boots;
	public static Item numenor2_bow;
	public static Item numenor2_chestplate;
	public static Item numenor2_crossbow;
	public static Item numenor2_dagger;
	public static Item numenor2_dagger_poisoned;
	public static Item numenor2_hammer;
	public static Item numenor2_helmet;
	public static Item numenor2_leggings;
	public static Item numenor2_pike;
	public static Item numenor2_spear;
	public static Item numenor2_sword;
	public static Item numenor3_boots;
	public static Item numenor3_chestplate;
	public static Item numenor3_helmet;
	public static Item numenor3_leggings;
	public static Item numenory_spear;
	public static Item onyx;
	public static Item onyxamy;
	public static Item perotaura;
	public static Item pineapple;
	public static Item raspberry;
	public static Item red_dwarven1_crossbow;
	public static Item red_dwarven2_boots;
	public static Item red_dwarven2_chestplate;
	public static Item red_dwarven2_crossbow;
	public static Item red_dwarven2_dagger;
	public static Item red_dwarven2_dagger_poisoned;
	public static Item red_dwarven2_hammer;
	public static Item red_dwarven2_helmet;
	public static Item red_dwarven2_leggings;
	public static Item red_dwarven2_pike;
	public static Item red_dwarven2_spear;
	public static Item red_dwarven2_sword;
	public static Item red_dwarven3_boots;
	public static Item red_dwarven3_chestplate;
	public static Item red_dwarven3_helmet;
	public static Item red_dwarven3_leggings;
	public static Item red_dwarveny_crossbow;
	public static Item redbag;
	public static Item rell1;
	public static Item rell2;
	public static Item rell3;
	public static Item rell4;
	public static Item rell5;
	public static Item rhovanion1_boots;
	public static Item rhovanion1_chestplate;
	public static Item rhovanion1_helmet;
	public static Item rhovanion1_leggings;
	public static Item rhovanion2_battleaxe;
	public static Item rhovanion2_boots;
	public static Item rhovanion2_bow;
	public static Item rhovanion2_chestplate;
	public static Item rhovanion2_dagger;
	public static Item rhovanion2_dagger_poisoned;
	public static Item rhovanion2_helmet;
	public static Item rhovanion2_leggings;
	public static Item rhovanion2_pike;
	public static Item rhovanion2_spear;
	public static Item rhovanion2_sword;
	public static Item rhovanion3_boots;
	public static Item rhovanion3_chestplate;
	public static Item rhovanion3_helmet;
	public static Item rhovanion3_leggings;
	public static Item rhovaniony_sword;
	public static Item rhubarb_pie;
	public static Item rhun2_bow;
	public static Item rhun2_dagger;
	public static Item rhun2_dagger_poisoned;
	public static Item rhun2_pike;
	public static Item rhun2_spear;
	public static Item rhun2_sword;
	public static Item rhun3_boots;
	public static Item rhun3_chestplate;
	public static Item rhun3_helmet;
	public static Item rhun3_leggings;
	public static Item rhuny_pike;
	public static Item ringgr;
	public static Item rubyamy;
	public static Item sapamy;
	public static Item sapamysilver;
	public static Item sibata1_boots;
	public static Item sibata1_chestplate;
	public static Item sibata1_helmet;
	public static Item sibata1_leggings;
	public static Item sibata2_boots;
	public static Item sibata2_chestplate;
	public static Item sibata2_helmet;
	public static Item sibata2_leggings;
	public static Item sibata3_boots;
	public static Item sibata3_chestplate;
	public static Item sibata3_helmet;
	public static Item sibata3_leggings;
	public static Item silveramy;
	public static Item sindar1_pike;
	public static Item sindar2_boots;
	public static Item sindar2_bow;
	public static Item sindar2_chestplate;
	public static Item sindar2_dagger;
	public static Item sindar2_dagger_poisoned;
	public static Item sindar2_helmet;
	public static Item sindar2_leggings;
	public static Item sindar2_pike;
	public static Item sindar2_polearm;
	public static Item sindar2_spear;
	public static Item sindar2_sword;
	public static Item sindar3_boots;
	public static Item sindar3_chestplate;
	public static Item sindar3_helmet;
	public static Item sindar3_leggings;
	public static Item sindary_pike;
	public static Item soul;
	public static Item spider;
	public static Item standart1_bow;
	public static Item standart1_crossbow;
	public static Item standart2_bow;
	public static Item standart2_crossbow;
	public static Item talisman;
	public static Item treasure_chest;
	public static Item ultraviolet_battleaxe;
	public static Item ultraviolet_boots;
	public static Item ultraviolet_chestplate;
	public static Item ultraviolet_helmet;
	public static Item ultraviolet_leggings;
	public static Item ultraviolet_sword;
	public static Item watermelon_cookies;
	public static Item weapon1;
	public static Item weapon2;
	public static Item weapon3;
	public static Item wiamy;
	public static Item wikey;
	public static Item wilock;
	public static Item witepearle;
	public static Item withamy;
	public static Item woodkey;
	public static Item woodlock;
	public static Item yelbag;

	public static void preInit() {
		ametamy = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		amogus = new LOTRItemSword(BDMaterial.numenor2).setCreativeTab(LOTRCreativeTabs.tabStory);
		apple_cookies = new LOTRItemFood(8, 1.0f, false);
		armorcoin1 = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		armorcoin2 = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		armorcoin3 = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		arrow_blindness = new BDItemArrowBlindness();
		arrow_fire = new BDItemArrowFire();
		arrow_hunger = new BDItemArrowHunger();
		arrow_slowness = new BDItemArrowSlowness();
		bbky1 = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		bbky2 = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		bblis1 = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		bblis2 = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		bblis3 = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		berry_cookies = new LOTRItemFood(8, 1.0f, false);
		blackbag = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		bluebag = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		bottle1 = new BDItemBottle1();
		bottle2 = new BDItemBottle2();
		bottle3 = new BDItemBottle3();
		chocolate_cookies = new LOTRItemFood(8, 1.0f, false);
		coin_dwarf = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		coin_enedwaith = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		coin_eregion = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		coin_eriador = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		coin_harad = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		coin_karndum = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		coin_khand = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		coin_mordor = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		coin_nandor = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		coin_noldor = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		coin_north = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		coin_numenor = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		coin_red_mountains = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		coin_rhovanion = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		coin_rhun = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		coin_sindar = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		crossbow_bolt_blindness = new LOTRItemCrossbowBolt().setBlindness();
		crossbow_bolt_fire = new LOTRItemCrossbowBolt().setFire();
		crossbow_bolt_hunger = new LOTRItemCrossbowBolt().setHunger();
		crossbow_bolt_slowness = new LOTRItemCrossbowBolt().setSlowness();
		crown = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		dark_boots = new BDItemArmor(BDMaterial.dark, 3);
		dark_bow = new LOTRItemBow(BDMaterial.dark);
		dark_chestplate = new BDItemArmor(BDMaterial.dark, 1, "chestplate");
		dark_crossbow = new LOTRItemCrossbow(BDMaterial.dark);
		dark_helmet = new BDItemArmor(BDMaterial.dark, 0, "helmet");
		dark_leggings = new BDItemArmor(BDMaterial.dark, 2);
		dark_spear = new LOTRItemSpear(BDMaterial.dark);
		dark_sword = new LOTRItemSword(BDMaterial.dark);
		darkgrove_boots = new BDItemArmor(BDMaterial.darkgrove, 3);
		darkgrove_bow = new LOTRItemBow(BDMaterial.darkgrove);
		darkgrove_chestplate = new BDItemArmor(BDMaterial.darkgrove, 1);
		darkgrove_helmet = new BDItemArmor(BDMaterial.darkgrove, 0);
		darkgrove_leggings = new BDItemArmor(BDMaterial.darkgrove, 2);
		darkgrove_pike = new LOTRItemPike(BDMaterial.darkgrove);
		darkgrove_sword = new LOTRItemSword(BDMaterial.darkgrove);
		dess = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		enedwaith1_bow = new LOTRItemBow(BDMaterial.enedwaith1);
		enedwaith1_crossbow = new LOTRItemCrossbow(BDMaterial.enedwaith1);
		enedwaith1_pike = new LOTRItemPike(BDMaterial.enedwaith1);
		enedwaith1_spear = new LOTRItemSpear(BDMaterial.enedwaith1);
		enedwaith1_sword = new LOTRItemSword(BDMaterial.enedwaith1);
		enedwaith2_boots = new BDItemArmor(BDMaterial.enedwaith2, 3);
		enedwaith2_bow = new LOTRItemBow(BDMaterial.enedwaith2).setDamageFactor(1.1);
		enedwaith2_chestplate = new BDItemArmor(BDMaterial.enedwaith2, 1);
		enedwaith2_crossbow = new LOTRItemCrossbow(BDMaterial.enedwaith2);
		enedwaith2_hammer = new LOTRItemHammer(BDMaterial.enedwaith2);
		enedwaith2_helmet = new BDItemArmor(BDMaterial.enedwaith2, 0);
		enedwaith2_leggings = new BDItemArmor(BDMaterial.enedwaith2, 2);
		enedwaith2_pike = new LOTRItemPike(BDMaterial.enedwaith2);
		enedwaith2_spear = new LOTRItemSpear(BDMaterial.enedwaith2);
		enedwaith2_sword = new LOTRItemSword(BDMaterial.enedwaith2);
		enedwaith3_boots = new BDItemArmor(BDMaterial.enedwaith3, 3);
		enedwaith3_chestplate = new BDItemArmor(BDMaterial.enedwaith3, 1);
		enedwaith3_helmet = new BDItemArmor(BDMaterial.enedwaith3, 0, "helmet");
		enedwaith3_leggings = new BDItemArmor(BDMaterial.enedwaith3, 2);
		enedwaithy_hammer = new LOTRItemHammer(BDMaterial.enedwaith3);
		eregion1_boots = new BDItemArmor(BDMaterial.eregion1, 3);
		eregion1_bow = new LOTRItemBow(BDMaterial.eregion1, 1.25).setDrawTime(16);
		eregion1_chestplate = new BDItemArmor(BDMaterial.eregion1, 1);
		eregion1_dagger = new LOTRItemDagger(BDMaterial.eregion1);
		eregion1_dagger_poisoned = new LOTRItemDagger(BDMaterial.eregion1, DaggerEffect.POISON);
		eregion1_helmet = new BDItemArmor(BDMaterial.eregion1, 0);
		eregion1_leggings = new BDItemArmor(BDMaterial.eregion1, 2);
		eregion1_pike = new LOTRItemPike(BDMaterial.eregion1);
		eregion1_polearm = new LOTRItemPolearm(BDMaterial.eregion1);
		eregion1_spear = new LOTRItemSpear(BDMaterial.eregion1);
		eregion1_sword = new LOTRItemSword(BDMaterial.eregion1);
		eregion2_boots = new BDItemArmor(BDMaterial.eregion2, 3);
		eregion2_bow = new LOTRItemBow(BDMaterial.eregion2, 1.35).setDrawTime(16);
		eregion2_chestplate = new BDItemArmor(BDMaterial.eregion2, 1);
		eregion2_dagger = new LOTRItemDagger(BDMaterial.eregion2);
		eregion2_dagger_poisoned = new LOTRItemDagger(BDMaterial.eregion2, DaggerEffect.POISON);
		eregion2_helmet = new BDItemArmor(BDMaterial.eregion2, 0);
		eregion2_leggings = new BDItemArmor(BDMaterial.eregion2, 2);
		eregion2_pike = new LOTRItemPike(BDMaterial.eregion2);
		eregion2_polearm = new LOTRItemPolearm(BDMaterial.eregion2);
		eregion2_spear = new LOTRItemSpear(BDMaterial.eregion2);
		eregion2_sword = new LOTRItemSword(BDMaterial.eregion2);
		eregion3_boots = new BDItemArmor(BDMaterial.eregion3, 3);
		eregion3_chestplate = new BDItemArmor(BDMaterial.eregion3, 1);
		eregion3_helmet = new BDItemArmor(BDMaterial.eregion3, 0);
		eregion3_leggings = new BDItemArmor(BDMaterial.eregion3, 2);
		eregiony_polearm = new LOTRItemPolearm(BDMaterial.eregion3);
		eriador1_boots = new BDItemArmor(BDMaterial.eriador1, 3);
		eriador1_bow = new LOTRItemBow(BDMaterial.eriador1, 1.2);
		eriador1_chestplate = new BDItemArmor(BDMaterial.eriador1, 1);
		eriador1_dagger = new LOTRItemDagger(BDMaterial.eriador1);
		eriador1_dagger_poisoned = new LOTRItemDagger(BDMaterial.eriador1, LOTRItemDagger.DaggerEffect.POISON);
		eriador1_hammer = new LOTRItemHammer(BDMaterial.eriador1);
		eriador1_helmet = new BDItemArmor(BDMaterial.eriador1, 0);
		eriador1_leggings = new BDItemArmor(BDMaterial.eriador1, 2);
		eriador1_pike = new LOTRItemPike(BDMaterial.eriador1);
		eriador1_spear = new LOTRItemSpear(BDMaterial.eriador1);
		eriador1_sword = new LOTRItemSword(BDMaterial.eriador1);
		eriador2_boots = new BDItemArmor(BDMaterial.eriador2, 3);
		eriador2_bow = new LOTRItemBow(BDMaterial.eriador2, 1.32);
		eriador2_chestplate = new BDItemArmor(BDMaterial.eriador2, 1);
		eriador2_dagger = new LOTRItemDagger(BDMaterial.eriador2);
		eriador2_dagger_poisoned = new LOTRItemDagger(BDMaterial.eriador2, LOTRItemDagger.DaggerEffect.POISON);
		eriador2_hammer = new LOTRItemHammer(BDMaterial.eriador2);
		eriador2_helmet = new BDItemArmor(BDMaterial.eriador2, 0);
		eriador2_leggings = new BDItemArmor(BDMaterial.eriador2, 2);
		eriador2_pike = new LOTRItemPike(BDMaterial.eriador2);
		eriador2_spear = new LOTRItemSpear(BDMaterial.eriador2);
		eriador2_sword = new LOTRItemSword(BDMaterial.eriador2);
		eriador3_boots = new BDItemArmor(BDMaterial.eriador3, 3);
		eriador3_chestplate = new BDItemArmor(BDMaterial.eriador3, 1);
		eriador3_helmet = new BDItemArmor(BDMaterial.eriador3, 0);
		eriador3_leggings = new BDItemArmor(BDMaterial.eriador3, 2);
		eriadory_hammer = new LOTRItemHammer(BDMaterial.eriador1);
		fish_arapaima = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_atlantic_cod = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_atlantic_halibut = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_atlantic_herring = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_bayad = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_blackfish = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_bluegill = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_boulti = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_brown_shrooma = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_brown_trout = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_capitaine = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_carp = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_catfish = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_fish_bones = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_goldfish = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_minnow = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_muskellunge = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_pacific_halibut = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_perch = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_pink_salmon = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_piranha = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_pollock = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_rainbow_trout = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_red_grouper = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_red_shrooma = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_smallmouth_bass = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_synodontis = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_tambaqui = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fish_tuna = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		fkris = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		fstone = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		goldamy = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		grapefruit = new LOTRItemFood(4, 0.3f, false);
		guardian_boots = new BDItemArmor(BDMaterial.guardian, 3);
		guardian_chestplate = new BDItemArmor(BDMaterial.guardian, 1);
		guardian_crossbow = new LOTRItemCrossbow(BDMaterial.guardian);
		guardian_dagger_poisoned = new LOTRItemDagger(BDMaterial.guardian, DaggerEffect.POISON);
		guardian_helmet = new BDItemArmor(BDMaterial.guardian, 0);
		guardian_leggings = new BDItemArmor(BDMaterial.guardian, 2);
		guardian_spear = new LOTRItemSpear(BDMaterial.guardian);
		harad2_boots = new BDItemArmor(BDMaterial.harad2, 3);
		harad2_bow = new LOTRItemBow(BDMaterial.harad2, 1.32);
		harad2_chestplate = new BDItemArmor(BDMaterial.harad2, 1);
		harad2_dagger = new LOTRItemDagger(BDMaterial.harad2);
		harad2_dagger_poisoned = new LOTRItemDagger(BDMaterial.harad2, DaggerEffect.POISON);
		harad2_hammer = new LOTRItemHammer(BDMaterial.harad2);
		harad2_helmet = new BDItemArmor(BDMaterial.harad2, 0);
		harad2_leggings = new BDItemArmor(BDMaterial.harad2, 2);
		harad2_pike = new LOTRItemPike(BDMaterial.harad2);
		harad2_spear = new LOTRItemSpear(BDMaterial.harad2);
		harad2_sword = new LOTRItemSword(BDMaterial.harad2);
		harad3_boots = new BDItemArmor(BDMaterial.harad3, 3);
		harad3_chestplate = new BDItemArmor(BDMaterial.harad3, 1);
		harad3_helmet = new BDItemArmor(BDMaterial.harad3, 0);
		harad3_leggings = new BDItemArmor(BDMaterial.harad3, 2);
		harady_dagger_poisoned = new LOTRItemDagger(BDMaterial.harad3, DaggerEffect.POISON);
		heal1 = new BDItemHeal1();
		heal2 = new BDItemHeal2();
		heal3 = new BDItemHeal3();
		honey_cookies = new LOTRItemFood(8, 1.0f, false);
		hors = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		irkey = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		irlock = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		jabroni = new Item().setCreativeTab(null);
		karndum1_bow = new LOTRItemBow(BDMaterial.karndum1, 1.2);
		karndum1_pike = new LOTRItemPike(BDMaterial.karndum1);
		karndum2_battleaxe = new LOTRItemBattleaxe(BDMaterial.karndum2);
		karndum2_boots = new BDItemArmor(BDMaterial.karndum2, 3);
		karndum2_bow = new LOTRItemBow(BDMaterial.karndum2, 1.32);
		karndum2_chestplate = new BDItemArmor(BDMaterial.karndum2, 1);
		karndum2_dagger = new LOTRItemDagger(BDMaterial.karndum1);
		karndum2_dagger_poisoned = new LOTRItemDagger(BDMaterial.karndum2, DaggerEffect.POISON);
		karndum2_hammer = new LOTRItemHammer(BDMaterial.karndum2);
		karndum2_helmet = new BDItemArmor(BDMaterial.karndum2, 0);
		karndum2_leggings = new BDItemArmor(BDMaterial.karndum2, 2);
		karndum2_pike = new LOTRItemPike(BDMaterial.karndum2);
		karndum2_spear = new LOTRItemSpear(BDMaterial.karndum2);
		karndum2_sword = new LOTRItemSword(BDMaterial.karndum2);
		karndum3_boots = new BDItemArmor(BDMaterial.karndum3, 3);
		karndum3_chestplate = new BDItemArmor(BDMaterial.karndum3, 1);
		karndum3_helmet = new BDItemArmor(BDMaterial.karndum3, 0, "helmet");
		karndum3_leggings = new BDItemArmor(BDMaterial.karndum3, 2);
		karndumy_sword = new LOTRItemSword(BDMaterial.karndum3);
		khand1_boots = new BDItemArmor(BDMaterial.khand1, 3);
		khand1_bow = new LOTRItemBow(BDMaterial.khand1).setDrawTime(14);
		khand1_chestplate = new BDItemArmor(BDMaterial.khand1, 1);
		khand1_dagger = new LOTRItemDagger(BDMaterial.khand1);
		khand1_dagger_poisoned = new LOTRItemDagger(BDMaterial.khand1, DaggerEffect.POISON);
		khand1_hammer = new LOTRItemHammer(BDMaterial.khand1);
		khand1_leggings = new BDItemArmor(BDMaterial.khand1, 2);
		khand1_pike = new LOTRItemPike(BDMaterial.khand1);
		khand1_spear = new LOTRItemSpear(BDMaterial.khand1);
		khand1_sword = new LOTRItemSword(BDMaterial.khand1);
		khand2_boots = new BDItemArmor(BDMaterial.khand2, 3);
		khand2_bow = new LOTRItemBow(BDMaterial.khand2).setDrawTime(14).setDamageFactor(1.1);
		khand2_chestplate = new BDItemArmor(BDMaterial.khand2, 1);
		khand2_dagger = new LOTRItemDagger(BDMaterial.khand2);
		khand2_dagger_poisoned = new LOTRItemDagger(BDMaterial.khand2, DaggerEffect.POISON);
		khand2_hammer = new LOTRItemHammer(BDMaterial.khand2);
		khand2_helmet = new BDItemArmor(BDMaterial.khand2, 0);
		khand2_leggings = new BDItemArmor(BDMaterial.khand2, 2);
		khand2_pike = new LOTRItemPike(BDMaterial.khand2);
		khand2_spear = new LOTRItemSpear(BDMaterial.khand2);
		khand2_sword = new LOTRItemSword(BDMaterial.khand2);
		khand3_boots = new BDItemArmor(BDMaterial.khand3, 3);
		khand3_chestplate = new BDItemArmor(BDMaterial.khand3, 1);
		khand3_leggings = new BDItemArmor(BDMaterial.khand3, 2);
		khandy_bow = new LOTRItemBow(BDMaterial.khand3).setDrawTime(14).setDamageFactor(1.2);
		khazad1_crossbow = new LOTRItemCrossbow(LOTRMaterial.URUK);
		khazad2_battleaxe = new LOTRItemBattleaxe(BDMaterial.khazad2);
		khazad2_boots = new BDItemArmor(BDMaterial.khazad2, 3);
		khazad2_chestplate = new BDItemArmor(BDMaterial.khazad2, 1);
		khazad2_crossbow = new LOTRItemCrossbow(LOTRMaterial.URUK);
		khazad2_dagger = new LOTRItemDagger(BDMaterial.khazad2);
		khazad2_dagger_poisoned = new LOTRItemDagger(BDMaterial.khazad2, LOTRItemDagger.DaggerEffect.POISON);
		khazad2_hammer = new LOTRItemHammer(BDMaterial.khazad2);
		khazad2_helmet = new BDItemArmor(BDMaterial.khazad2, 0, "helmet");
		khazad2_leggings = new BDItemArmor(BDMaterial.khazad2, 2);
		khazad2_pike = new LOTRItemPike(BDMaterial.khazad2);
		khazad2_spear = new LOTRItemSpear(BDMaterial.khazad2);
		khazad2_sword = new LOTRItemSword(BDMaterial.khazad2);
		khazad3_boots = new BDItemArmor(BDMaterial.khazad3, 3);
		khazad3_chestplate = new BDItemArmor(BDMaterial.khazad3, 1);
		khazad3_helmet = new BDItemArmor(BDMaterial.khazad3, 0, "helmet");
		khazad3_leggings = new BDItemArmor(BDMaterial.khazad3, 2);
		khazady_crossbow = new LOTRItemCrossbow(LOTRMaterial.MITHRIL);
		kiwi = new LOTRItemFood(4, 0.3f, false);
		krest = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		kris = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		light_boots = new BDItemArmor(BDMaterial.light, 3);
		light_bow = new LOTRItemBow(BDMaterial.light);
		light_chestplate = new BDItemArmor(BDMaterial.light, 1, "chestplate");
		light_crossbow = new LOTRItemCrossbow(BDMaterial.light);
		light_helmet = new BDItemArmor(BDMaterial.light, 0, "helmet");
		light_leggings = new BDItemArmor(BDMaterial.light, 2);
		light_spear = new LOTRItemSpear(BDMaterial.light);
		light_sword = new LOTRItemSword(BDMaterial.light);
		manykey = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		maple_leaf = new Item().setCreativeTab(BDCreativeTabs.tabFood);
		milk_cookies = new LOTRItemFood(8, 1.0f, false);
		mirror = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		mordor2_boots = new BDItemArmor(BDMaterial.mordor2, 3);
		mordor2_chestplate = new BDItemArmor(BDMaterial.mordor2, 1, "chestplate");
		mordor2_helmet = new BDItemArmor(BDMaterial.mordor2, 0, "helmet");
		mordor2_leggings = new BDItemArmor(BDMaterial.mordor2, 2);
		mordor2_polearm = new LOTRItemBattleaxe(BDMaterial.mordor2);
		mordory_spear = new LOTRItemSpear(BDMaterial.mordor3);
		mug_maple = new LOTRItemMug(0.0f).setDrinkStats(6, 0.6f).addPotionEffect(Potion.damageBoost.id, 60).addPotionEffect(Potion.moveSpeed.id, 60).setDamageAmount(2).setCreativeTab(BDCreativeTabs.tabFood);
		nandor1_pike = new LOTRItemPike(BDMaterial.nandor1);
		nandor2_boots = new BDItemArmor(BDMaterial.nandor2, 3);
		nandor2_bow = new LOTRItemBow(BDMaterial.nandor2).setDamageFactor(1.1);
		nandor2_chestplate = new BDItemArmor(BDMaterial.nandor2, 1);
		nandor2_dagger = new LOTRItemDagger(BDMaterial.nandor2);
		nandor2_dagger_poisoned = new LOTRItemDagger(BDMaterial.nandor2, DaggerEffect.POISON);
		nandor2_helmet = new BDItemArmor(BDMaterial.nandor2, 0, "helmet");
		nandor2_leggings = new BDItemArmor(BDMaterial.nandor2, 2);
		nandor2_pike = new LOTRItemPike(BDMaterial.nandor2);
		nandor2_polearm = new LOTRItemPolearm(BDMaterial.nandor2);
		nandor2_spear = new LOTRItemSpear(BDMaterial.nandor2);
		nandor2_sword = new LOTRItemSword(BDMaterial.nandor2);
		nandor3_boots = new BDItemArmor(BDMaterial.nandor3, 3);
		nandor3_chestplate = new BDItemArmor(BDMaterial.nandor3, 1);
		nandor3_helmet = new BDItemArmor(BDMaterial.nandor3, 0, "helmet");
		nandor3_leggings = new BDItemArmor(BDMaterial.nandor3, 2);
		nandory_bow = new LOTRItemBow(BDMaterial.nandor3).setDamageFactor(1.2);
		noldor1_pike = new LOTRItemPike(BDMaterial.noldor1);
		noldor2_boots = new BDItemArmor(BDMaterial.noldor2, 3);
		noldor2_bow = new LOTRItemBow(BDMaterial.noldor2, 1.35).setDrawTime(16);
		noldor2_chestplate = new BDItemArmor(BDMaterial.noldor2, 1);
		noldor2_dagger = new LOTRItemDagger(BDMaterial.noldor2);
		noldor2_dagger_poisoned = new LOTRItemDagger(BDMaterial.noldor2, LOTRItemDagger.DaggerEffect.POISON);
		noldor2_helmet = new BDItemArmor(BDMaterial.noldor2, 0);
		noldor2_leggings = new BDItemArmor(BDMaterial.noldor2, 2);
		noldor2_pike = new LOTRItemPike(BDMaterial.noldor2);
		noldor2_polearm = new LOTRItemPolearm(BDMaterial.noldor2);
		noldor2_spear = new LOTRItemSpear(BDMaterial.noldor2);
		noldor2_sword = new LOTRItemSword(BDMaterial.noldor2);
		noldor3_boots = new BDItemArmor(BDMaterial.noldor3, 3);
		noldor3_chestplate = new BDItemArmor(BDMaterial.noldor3, 1);
		noldor3_helmet = new BDItemArmor(BDMaterial.noldor3, 0);
		noldor3_leggings = new BDItemArmor(BDMaterial.noldor3, 2);
		noldory_sword = new LOTRItemSword(BDMaterial.noldor3);
		north2_boots = new BDItemArmor(BDMaterial.north2, 3);
		north2_bow = new LOTRItemBow(BDMaterial.north2, 1.32);
		north2_chestplate = new BDItemArmor(BDMaterial.north2, 1);
		north2_dagger = new LOTRItemDagger(BDMaterial.north2);
		north2_dagger_poisoned = new LOTRItemDagger(BDMaterial.north2, LOTRItemDagger.DaggerEffect.POISON);
		north2_hammer = new LOTRItemHammer(BDMaterial.north2);
		north2_helmet = new BDItemArmor(BDMaterial.north2, 0);
		north2_leggings = new BDItemArmor(BDMaterial.north2, 2);
		north2_pike = new LOTRItemPike(BDMaterial.north2);
		north2_spear = new LOTRItemSpear(BDMaterial.north2);
		north2_sword = new LOTRItemSword(BDMaterial.north2);
		north3_boots = new BDItemArmor(BDMaterial.north3, 3);
		north3_chestplate = new BDItemArmor(BDMaterial.north3, 1);
		north3_helmet = new BDItemArmor(BDMaterial.north3, 0, "helmet");
		north3_leggings = new BDItemArmor(BDMaterial.north3, 2);
		northy_sword = new LOTRItemSword(BDMaterial.north3);
		numenor1_battleaxe = new LOTRItemBattleaxe(BDMaterial.numenor1);
		numenor1_crossbow = new LOTRItemCrossbow(BDMaterial.numenor1);
		numenor2_battleaxe = new LOTRItemBattleaxe(BDMaterial.numenor1);
		numenor2_boots = new BDItemArmor(BDMaterial.numenor2, 3);
		numenor2_bow = new LOTRItemBow(BDMaterial.numenor2).setDrawTime(16).setDamageFactor(1.1);
		numenor2_chestplate = new BDItemArmor(BDMaterial.numenor2, 1);
		numenor2_crossbow = new LOTRItemCrossbow(BDMaterial.numenor2);
		numenor2_dagger = new LOTRItemDagger(BDMaterial.numenor2);
		numenor2_dagger_poisoned = new LOTRItemDagger(BDMaterial.numenor2, LOTRItemDagger.DaggerEffect.POISON);
		numenor2_hammer = new LOTRItemHammer(BDMaterial.numenor2);
		numenor2_helmet = new BDItemArmor(BDMaterial.numenor2, 0, "helmet");
		numenor2_leggings = new BDItemArmor(BDMaterial.numenor2, 2);
		numenor2_pike = new LOTRItemPike(BDMaterial.numenor2);
		numenor2_spear = new LOTRItemSpear(BDMaterial.numenor2);
		numenor2_sword = new LOTRItemSword(BDMaterial.numenor2);
		numenor3_boots = new BDItemArmor(BDMaterial.numenor3, 3);
		numenor3_chestplate = new BDItemArmor(BDMaterial.numenor3, 1, "chestplate");
		numenor3_helmet = new BDItemArmor(BDMaterial.numenor3, 0, "helmet");
		numenor3_leggings = new BDItemArmor(BDMaterial.numenor3, 2);
		numenory_spear = new LOTRItemSpear(BDMaterial.numenor3);
		onyx = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		onyxamy = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		perotaura = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		pineapple = new LOTRItemFood(4, 0.3f, false);
		raspberry = new LOTRItemFood(4, 0.3f, false);
		red_dwarven1_crossbow = new LOTRItemCrossbow(LOTRMaterial.URUK);
		red_dwarven2_boots = new BDItemArmor(BDMaterial.red_dwarven2, 3);
		red_dwarven2_chestplate = new BDItemArmor(BDMaterial.red_dwarven2, 1);
		red_dwarven2_crossbow = new LOTRItemCrossbow(LOTRMaterial.URUK);
		red_dwarven2_dagger = new LOTRItemDagger(BDMaterial.red_dwarven2);
		red_dwarven2_dagger_poisoned = new LOTRItemDagger(BDMaterial.red_dwarven2, DaggerEffect.POISON);
		red_dwarven2_hammer = new LOTRItemHammer(BDMaterial.red_dwarven2);
		red_dwarven2_helmet = new BDItemArmor(BDMaterial.red_dwarven2, 0, "helmet");
		red_dwarven2_leggings = new BDItemArmor(BDMaterial.red_dwarven2, 2);
		red_dwarven2_pike = new LOTRItemPike(BDMaterial.red_dwarven2);
		red_dwarven2_spear = new LOTRItemSpear(BDMaterial.red_dwarven2);
		red_dwarven2_sword = new LOTRItemSword(BDMaterial.red_dwarven2);
		red_dwarven3_boots = new BDItemArmor(BDMaterial.red_dwarven3, 3);
		red_dwarven3_chestplate = new BDItemArmor(BDMaterial.red_dwarven3, 1);
		red_dwarven3_helmet = new BDItemArmor(BDMaterial.red_dwarven3, 0, "helmet");
		red_dwarven3_leggings = new BDItemArmor(BDMaterial.red_dwarven3, 2);
		red_dwarveny_crossbow = new LOTRItemCrossbow(LOTRMaterial.MITHRIL);
		redbag = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		rell1 = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		rell2 = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		rell3 = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		rell4 = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		rell5 = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		rhovanion1_boots = new BDItemArmor(BDMaterial.rhovanion1, 3);
		rhovanion1_chestplate = new BDItemArmor(BDMaterial.rhovanion1, 1);
		rhovanion1_helmet = new BDItemArmor(BDMaterial.rhovanion1, 0);
		rhovanion1_leggings = new BDItemArmor(BDMaterial.rhovanion1, 2);
		rhovanion2_battleaxe = new LOTRItemBattleaxe(BDMaterial.rhovanion2);
		rhovanion2_boots = new BDItemArmor(BDMaterial.rhovanion2, 3);
		rhovanion2_bow = new LOTRItemBow(BDMaterial.rhovanion2, 1.32);
		rhovanion2_chestplate = new BDItemArmor(BDMaterial.rhovanion2, 1);
		rhovanion2_dagger = new LOTRItemDagger(BDMaterial.rhovanion2);
		rhovanion2_dagger_poisoned = new LOTRItemDagger(BDMaterial.rhovanion2, LOTRItemDagger.DaggerEffect.POISON);
		rhovanion2_helmet = new BDItemArmor(BDMaterial.rhovanion2, 0);
		rhovanion2_leggings = new BDItemArmor(BDMaterial.rhovanion2, 2);
		rhovanion2_pike = new LOTRItemPike(BDMaterial.rhovanion2);
		rhovanion2_spear = new LOTRItemSword(BDMaterial.rhovanion2);
		rhovanion2_sword = new LOTRItemSpear(BDMaterial.rhovanion2);
		rhovanion3_boots = new BDItemArmor(BDMaterial.rhovanion3, 3);
		rhovanion3_chestplate = new BDItemArmor(BDMaterial.rhovanion3, 1);
		rhovanion3_helmet = new BDItemArmor(BDMaterial.rhovanion3, 0, "helmet");
		rhovanion3_leggings = new BDItemArmor(BDMaterial.rhovanion3, 2);
		rhovaniony_sword = new LOTRItemSword(BDMaterial.rhovanion3);
		rhubarb_pie = new LOTRItemFood(8, 1.0f, false);
		rhun2_bow = new LOTRItemBow(BDMaterial.rhun2).setDrawTime(16).setDamageFactor(1.1);
		rhun2_dagger = new LOTRItemDagger(BDMaterial.rhun2);
		rhun2_dagger_poisoned = new LOTRItemDagger(BDMaterial.rhun2, DaggerEffect.POISON);
		rhun2_pike = new LOTRItemPike(BDMaterial.rhun2);
		rhun2_spear = new LOTRItemSpear(BDMaterial.rhun2);
		rhun2_sword = new LOTRItemSword(BDMaterial.rhun2);
		rhun3_boots = new BDItemArmor(BDMaterial.rhun3, 3);
		rhun3_chestplate = new BDItemArmor(BDMaterial.rhun3, 1);
		rhun3_helmet = new BDItemArmor(BDMaterial.rhun3, 0, "helmet");
		rhun3_leggings = new BDItemArmor(BDMaterial.rhun3, 2);
		rhuny_pike = new LOTRItemPike(BDMaterial.rhun2);
		ringgr = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		rubyamy = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		sapamy = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		sapamysilver = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		sibata1_boots = new BDItemArmor(BDMaterial.sibata1, 3);
		sibata1_chestplate = new BDItemArmor(BDMaterial.sibata1, 1);
		sibata1_helmet = new BDItemArmor(BDMaterial.sibata1, 0, "helmet");
		sibata1_leggings = new BDItemArmor(BDMaterial.sibata1, 2);
		sibata2_boots = new BDItemArmor(BDMaterial.sibata2, 3);
		sibata2_chestplate = new BDItemArmor(BDMaterial.sibata2, 1);
		sibata2_helmet = new BDItemArmor(BDMaterial.sibata2, 0, "helmet");
		sibata2_leggings = new BDItemArmor(BDMaterial.sibata2, 2);
		sibata3_boots = new BDItemArmor(BDMaterial.sibata3, 3);
		sibata3_chestplate = new BDItemArmor(BDMaterial.sibata3, 1);
		sibata3_helmet = new BDItemArmor(BDMaterial.sibata3, 0, "helmet");
		sibata3_leggings = new BDItemArmor(BDMaterial.sibata3, 2);
		silveramy = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		sindar1_pike = new LOTRItemPike(BDMaterial.sindar1);
		sindar2_boots = new BDItemArmor(BDMaterial.sindar2, 3);
		sindar2_bow = new LOTRItemBow(BDMaterial.sindar2, 1.35).setDrawTime(16);
		sindar2_chestplate = new BDItemArmor(BDMaterial.sindar2, 1);
		sindar2_dagger = new LOTRItemDagger(BDMaterial.sindar2);
		sindar2_dagger_poisoned = new LOTRItemDagger(BDMaterial.sindar2, DaggerEffect.POISON);
		sindar2_helmet = new BDItemArmor(BDMaterial.sindar2, 0, "helmet");
		sindar2_leggings = new BDItemArmor(BDMaterial.sindar2, 2);
		sindar2_pike = new LOTRItemPike(BDMaterial.sindar2);
		sindar2_polearm = new LOTRItemPolearm(BDMaterial.sindar2);
		sindar2_spear = new LOTRItemSpear(BDMaterial.sindar2);
		sindar2_sword = new LOTRItemSword(BDMaterial.sindar2);
		sindar3_boots = new BDItemArmor(BDMaterial.sindar3, 3);
		sindar3_chestplate = new BDItemArmor(BDMaterial.sindar3, 1);
		sindar3_helmet = new BDItemArmor(BDMaterial.sindar3, 0, "helmet");
		sindar3_leggings = new BDItemArmor(BDMaterial.sindar3, 2);
		sindary_pike = new LOTRItemPike(BDMaterial.sindar3);
		soul = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		spider = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		standart1_bow = new LOTRItemBow(LOTRMaterial.RANGER);
		standart1_crossbow = new LOTRItemCrossbow(ToolMaterial.IRON);
		standart2_bow = new LOTRItemBow(LOTRMaterial.RANGER).setDamageFactor(1.1);
		standart2_crossbow = new LOTRItemCrossbow(ToolMaterial.IRON);
		table_eregion = new BDBlockTableEregion();
		table_khand = new BDBlockTableKhand();
		talisman = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		treasure_chest = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		ultraviolet_battleaxe = new LOTRItemBattleaxe(BDMaterial.ultraviolet);
		ultraviolet_boots = new BDItemArmor(BDMaterial.ultraviolet, 3, "boots");
		ultraviolet_chestplate = new BDItemArmor(BDMaterial.ultraviolet, 1, "chestplate");
		ultraviolet_helmet = new BDItemArmor(BDMaterial.ultraviolet, 0, "helmet");
		ultraviolet_leggings = new BDItemArmor(BDMaterial.ultraviolet, 2);
		ultraviolet_sword = new LOTRItemSword(BDMaterial.ultraviolet);
		watermelon_cookies = new LOTRItemFood(8, 1.0f, false);
		weapon1 = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		weapon2 = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		weapon3 = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		wiamy = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		wikey = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		wilock = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		witepearle = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		withamy = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		woodkey = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		woodlock = new Item().setCreativeTab(BDCreativeTabs.tabAnus);
		yelbag = new Item().setCreativeTab(BDCreativeTabs.tabAnus);

		BDPatcher.patchInventory();

		WOTRMCNewBlocks.initializeNewBlocks();
		WOTRMCNewBlocks.initializeNewBlocks2();

		registerBlock(table_eregion, "table_eregion");
		registerBlock(table_khand, "table_khand");

		registerItemLotr(mug_maple, "mug_maple");

		register(amogus, "amogus");
		register(ametamy, "ametamy");
		register(armorcoin1, "armorcoin1");
		register(armorcoin2, "armorcoin2");
		register(armorcoin3, "armorcoin3");
		register(bbky1, "bbky1");
		register(bbky2, "bbky2");
		register(bblis1, "bblis1");
		register(bblis2, "bblis2");
		register(bblis3, "bblis3");
		register(blackbag, "blackbag");
		register(bluebag, "bluebag");
		register(crown, "crown");
		register(dess, "dess");
		register(fkris, "fkris");
		register(fstone, "fstone");
		register(goldamy, "goldamy");
		register(hors, "hors");
		register(irkey, "irkey");
		register(irlock, "irlock");
		register(krest, "krest");
		register(kris, "kris");
		register(manykey, "manykey");
		register(mirror, "mirror");
		register(onyx, "onyx");
		register(onyxamy, "onyxamy");
		register(perotaura, "perotaura");
		register(redbag, "redbag");
		register(rell1, "rell1");
		register(rell2, "rell2");
		register(rell3, "rell3");
		register(rell4, "rell4");
		register(rell5, "rell5");
		register(ringgr, "ringgr");
		register(rubyamy, "rubyamy");
		register(sapamy, "sapamy");
		register(sapamysilver, "sapamysilver");
		register(silveramy, "silveramy");
		register(soul, "soul");
		register(spider, "spider");
		register(talisman, "talisman");
		register(weapon1, "weapon1");
		register(weapon2, "weapon2");
		register(weapon3, "weapon3");
		register(wiamy, "wiamy");
		register(wikey, "wikey");
		register(wilock, "wilock");
		register(witepearle, "witepearle");
		register(withamy, "withamy");
		register(woodkey, "woodkey");
		register(woodlock, "woodlock");
		register(yelbag, "yelbag");
		register(coin_karndum, "coin_karndum");
		register(coin_dwarf, "coin_dwarf");
		register(coin_enedwaith, "coin_enedwaith");
		register(coin_eregion, "coin_eregion");
		register(coin_eriador, "coin_eriador");
		register(coin_harad, "coin_harad");
		register(coin_khand, "coin_khand");
		register(coin_mordor, "coin_mordor");
		register(coin_nandor, "coin_nandor");
		register(coin_noldor, "coin_noldor");
		register(coin_north, "coin_north");
		register(coin_numenor, "coin_numenor");
		register(coin_red_mountains, "coin_red_mountains");
		register(coin_rhovanion, "coin_rhovanion");
		register(coin_rhun, "coin_rhun");
		register(coin_sindar, "coin_sindar");

		register(dark_helmet, "dark_helmet");
		register(dark_chestplate, "dark_chestplate");
		register(dark_leggings, "dark_leggings");
		register(dark_boots, "dark_boots");

		register(darkgrove_helmet, "darkgrove_helmet");
		register(darkgrove_chestplate, "darkgrove_chestplate");
		register(darkgrove_leggings, "darkgrove_leggings");
		register(darkgrove_boots, "darkgrove_boots");

		register(enedwaith2_helmet, "enedwaith2_helmet");
		register(enedwaith2_chestplate, "enedwaith2_chestplate");
		register(enedwaith2_leggings, "enedwaith2_leggings");
		register(enedwaith2_boots, "enedwaith2_boots");

		register(enedwaith3_helmet, "enedwaith3_helmet");
		register(enedwaith3_chestplate, "enedwaith3_chestplate");
		register(enedwaith3_leggings, "enedwaith3_leggings");
		register(enedwaith3_boots, "enedwaith3_boots");

		register(eregion1_helmet, "eregion1_helmet");
		register(eregion1_chestplate, "eregion1_chestplate");
		register(eregion1_leggings, "eregion1_leggings");
		register(eregion1_boots, "eregion1_boots");

		register(eregion2_helmet, "eregion2_helmet");
		register(eregion2_chestplate, "eregion2_chestplate");
		register(eregion2_leggings, "eregion2_leggings");
		register(eregion2_boots, "eregion2_boots");

		register(eregion3_helmet, "eregion3_helmet");
		register(eregion3_chestplate, "eregion3_chestplate");
		register(eregion3_leggings, "eregion3_leggings");
		register(eregion3_boots, "eregion3_boots");

		register(eriador1_helmet, "eriador1_helmet");
		register(eriador1_chestplate, "eriador1_chestplate");
		register(eriador1_leggings, "eriador1_leggings");
		register(eriador1_boots, "eriador1_boots");

		register(eriador2_helmet, "eriador2_helmet");
		register(eriador2_chestplate, "eriador2_chestplate");
		register(eriador2_leggings, "eriador2_leggings");
		register(eriador2_boots, "eriador2_boots");

		register(eriador3_helmet, "eriador3_helmet");
		register(eriador3_chestplate, "eriador3_chestplate");
		register(eriador3_leggings, "eriador3_leggings");
		register(eriador3_boots, "eriador3_boots");

		register(guardian_helmet, "guardian_helmet");
		register(guardian_chestplate, "guardian_chestplate");
		register(guardian_leggings, "guardian_leggings");
		register(guardian_boots, "guardian_boots");

		register(harad2_helmet, "harad2_helmet");
		register(harad2_chestplate, "harad2_chestplate");
		register(harad2_leggings, "harad2_leggings");
		register(harad2_boots, "harad2_boots");

		register(harad3_helmet, "harad3_helmet");
		register(harad3_chestplate, "harad3_chestplate");
		register(harad3_leggings, "harad3_leggings");
		register(harad3_boots, "harad3_boots");

		register(karndum2_helmet, "karndum2_helmet");
		register(karndum2_chestplate, "karndum2_chestplate");
		register(karndum2_leggings, "karndum2_leggings");
		register(karndum2_boots, "karndum2_boots");

		register(karndum3_helmet, "karndum3_helmet");
		register(karndum3_chestplate, "karndum3_chestplate");
		register(karndum3_leggings, "karndum3_leggings");
		register(karndum3_boots, "karndum3_boots");

		register(khand1_chestplate, "khand1_chestplate");
		register(khand1_leggings, "khand1_leggings");
		register(khand1_boots, "khand1_boots");

		register(khand2_helmet, "khand2_helmet");
		register(khand2_chestplate, "khand2_chestplate");
		register(khand2_leggings, "khand2_leggings");
		register(khand2_boots, "khand2_boots");

		register(khand3_chestplate, "khand3_chestplate");
		register(khand3_leggings, "khand3_leggings");
		register(khand3_boots, "khand3_boots");

		register(khazad2_helmet, "khazad2_helmet");
		register(khazad2_chestplate, "khazad2_chestplate");
		register(khazad2_leggings, "khazad2_leggings");
		register(khazad2_boots, "khazad2_boots");

		register(khazad3_helmet, "khazad3_helmet");
		register(khazad3_chestplate, "khazad3_chestplate");
		register(khazad3_leggings, "khazad3_leggings");
		register(khazad3_boots, "khazad3_boots");

		register(light_helmet, "light_helmet");
		register(light_chestplate, "light_chestplate");
		register(light_leggings, "light_leggings");
		register(light_boots, "light_boots");

		register(mordor2_helmet, "mordor2_helmet");
		register(mordor2_chestplate, "mordor2_chestplate");
		register(mordor2_leggings, "mordor2_leggings");
		register(mordor2_boots, "mordor2_boots");

		register(nandor2_helmet, "nandor2_helmet");
		register(nandor2_chestplate, "nandor2_chestplate");
		register(nandor2_leggings, "nandor2_leggings");
		register(nandor2_boots, "nandor2_boots");

		register(nandor3_helmet, "nandor3_helmet");
		register(nandor3_chestplate, "nandor3_chestplate");
		register(nandor3_leggings, "nandor3_leggings");
		register(nandor3_boots, "nandor3_boots");

		register(noldor2_helmet, "noldor2_helmet");
		register(noldor2_chestplate, "noldor2_chestplate");
		register(noldor2_leggings, "noldor2_leggings");
		register(noldor2_boots, "noldor2_boots");

		register(noldor3_helmet, "noldor3_helmet");
		register(noldor3_chestplate, "noldor3_chestplate");
		register(noldor3_leggings, "noldor3_leggings");
		register(noldor3_boots, "noldor3_boots");

		register(north2_helmet, "north2_helmet");
		register(north2_chestplate, "north2_chestplate");
		register(north2_leggings, "north2_leggings");
		register(north2_boots, "north2_boots");

		register(north3_helmet, "north3_helmet");
		register(north3_chestplate, "north3_chestplate");
		register(north3_leggings, "north3_leggings");
		register(north3_boots, "north3_boots");

		register(numenor2_helmet, "numenor2_helmet");
		register(numenor2_chestplate, "numenor2_chestplate");
		register(numenor2_leggings, "numenor2_leggings");
		register(numenor2_boots, "numenor2_boots");

		register(numenor3_helmet, "numenor3_helmet");
		register(numenor3_chestplate, "numenor3_chestplate");
		register(numenor3_leggings, "numenor3_leggings");
		register(numenor3_boots, "numenor3_boots");

		register(red_dwarven2_helmet, "red_dwarven2_helmet");
		register(red_dwarven2_chestplate, "red_dwarven2_chestplate");
		register(red_dwarven2_leggings, "red_dwarven2_leggings");
		register(red_dwarven2_boots, "red_dwarven2_boots");

		register(red_dwarven3_helmet, "red_dwarven3_helmet");
		register(red_dwarven3_chestplate, "red_dwarven3_chestplate");
		register(red_dwarven3_leggings, "red_dwarven3_leggings");
		register(red_dwarven3_boots, "red_dwarven3_boots");

		register(rhovanion1_helmet, "rhovanion1_helmet");
		register(rhovanion1_chestplate, "rhovanion1_chestplate");
		register(rhovanion1_leggings, "rhovanion1_leggings");
		register(rhovanion1_boots, "rhovanion1_boots");

		register(rhovanion2_helmet, "rhovanion2_helmet");
		register(rhovanion2_chestplate, "rhovanion2_chestplate");
		register(rhovanion2_leggings, "rhovanion2_leggings");
		register(rhovanion2_boots, "rhovanion2_boots");

		register(rhovanion3_helmet, "rhovanion3_helmet");
		register(rhovanion3_chestplate, "rhovanion3_chestplate");
		register(rhovanion3_leggings, "rhovanion3_leggings");
		register(rhovanion3_boots, "rhovanion3_boots");

		register(rhun3_helmet, "rhun3_helmet");
		register(rhun3_chestplate, "rhun3_chestplate");
		register(rhun3_leggings, "rhun3_leggings");
		register(rhun3_boots, "rhun3_boots");

		register(sibata1_helmet, "sibata1_helmet");
		register(sibata1_chestplate, "sibata1_chestplate");
		register(sibata1_leggings, "sibata1_leggings");
		register(sibata1_boots, "sibata1_boots");

		register(sibata2_helmet, "sibata2_helmet");
		register(sibata2_chestplate, "sibata2_chestplate");
		register(sibata2_leggings, "sibata2_leggings");
		register(sibata2_boots, "sibata2_boots");

		register(sibata3_helmet, "sibata3_helmet");
		register(sibata3_chestplate, "sibata3_chestplate");
		register(sibata3_leggings, "sibata3_leggings");
		register(sibata3_boots, "sibata3_boots");

		register(sindar2_helmet, "sindar2_helmet");
		register(sindar2_chestplate, "sindar2_chestplate");
		register(sindar2_leggings, "sindar2_leggings");
		register(sindar2_boots, "sindar2_boots");

		register(sindar3_helmet, "sindar3_helmet");
		register(sindar3_chestplate, "sindar3_chestplate");
		register(sindar3_leggings, "sindar3_leggings");
		register(sindar3_boots, "sindar3_boots");

		register(ultraviolet_helmet, "ultraviolet_helmet");
		register(ultraviolet_chestplate, "ultraviolet_chestplate");
		register(ultraviolet_leggings, "ultraviolet_leggings");
		register(ultraviolet_boots, "ultraviolet_boots");

		register(enedwaith1_bow, "enedwaith1_bow");
		register(enedwaith1_crossbow, "enedwaith1_crossbow");
		register(enedwaith1_pike, "enedwaith1_pike");
		register(enedwaith1_spear, "enedwaith1_spear");
		register(enedwaith1_sword, "enedwaith1_sword");
		register(enedwaith2_bow, "enedwaith2_bow");
		register(enedwaith2_crossbow, "enedwaith2_crossbow");
		register(enedwaith2_hammer, "enedwaith2_hammer");
		register(enedwaith2_pike, "enedwaith2_pike");
		register(enedwaith2_spear, "enedwaith2_spear");
		register(enedwaith2_sword, "enedwaith2_sword");
		register(enedwaithy_hammer, "enedwaithy_hammer");
		register(eregion1_bow, "eregion1_bow");
		register(eregion1_dagger, "eregion1_dagger");
		register(eregion1_dagger_poisoned, "eregion1_dagger_poisoned");
		register(eregion1_pike, "eregion1_pike");
		register(eregion1_polearm, "eregion1_polearm");
		register(eregion1_spear, "eregion1_spear");
		register(eregion1_sword, "eregion1_sword");
		register(eregion2_bow, "eregion2_bow");
		register(eregion2_dagger, "eregion2_dagger");
		register(eregion2_dagger_poisoned, "eregion2_dagger_poisoned");
		register(eregion2_pike, "eregion2_pike");
		register(eregion2_polearm, "eregion2_polearm");
		register(eregion2_spear, "eregion2_spear");
		register(eregion2_sword, "eregion2_sword");
		register(eregiony_polearm, "eregiony_polearm");
		register(eriador1_bow, "eriador1_bow");
		register(eriador1_dagger, "eriador1_dagger");
		register(eriador1_dagger_poisoned, "eriador1_dagger_poisoned");
		register(eriador1_hammer, "eriador1_hammer");
		register(eriador1_pike, "eriador1_pike");
		register(eriador1_spear, "eriador1_spear");
		register(eriador1_sword, "eriador1_sword");
		register(eriador2_bow, "eriador2_bow");
		register(eriador2_dagger, "eriador2_dagger");
		register(eriador2_dagger_poisoned, "eriador2_dagger_poisoned");
		register(eriador2_hammer, "eriador2_hammer");
		register(eriador2_pike, "eriador2_pike");
		register(eriador2_spear, "eriador2_spear");
		register(eriador2_sword, "eriador2_sword");
		register(eriadory_hammer, "eriadory_hammer");
		register(harad2_bow, "harad2_bow");
		register(harad2_dagger, "harad2_dagger");
		register(harad2_dagger_poisoned, "harad2_dagger_poisoned");
		register(harad2_hammer, "harad2_hammer");
		register(harad2_pike, "harad2_pike");
		register(harad2_spear, "harad2_spear");
		register(harad2_sword, "harad2_sword");
		register(harady_dagger_poisoned, "harady_dagger_poisoned");
		register(karndum1_bow, "karndum1_bow");
		register(karndum1_pike, "karndum1_pike");
		register(karndum2_battleaxe, "karndum2_battleaxe");
		register(karndum2_bow, "karndum2_bow");
		register(karndum2_dagger, "karndum2_dagger");
		register(karndum2_dagger_poisoned, "karndum2_dagger_poisoned");
		register(karndum2_hammer, "karndum2_hammer");
		register(karndum2_pike, "karndum2_pike");
		register(karndum2_spear, "karndum2_spear");
		register(karndum2_sword, "karndum2_sword");
		register(karndumy_sword, "karndumy_sword");
		register(khand1_bow, "khand1_bow");
		register(khand1_dagger, "khand1_dagger");
		register(khand1_dagger_poisoned, "khand1_dagger_poisoned");
		register(khand1_hammer, "khand1_hammer");
		register(khand1_pike, "khand1_pike");
		register(khand1_spear, "khand1_spear");
		register(khand1_sword, "khand1_sword");
		register(khand2_bow, "khand2_bow");
		register(khand2_dagger, "khand2_dagger");
		register(khand2_dagger_poisoned, "khand2_dagger_poisoned");
		register(khand2_hammer, "khand2_hammer");
		register(khand2_pike, "khand2_pike");
		register(khand2_spear, "khand2_spear");
		register(khand2_sword, "khand2_sword");
		register(khandy_bow, "khandy_bow");
		register(khazad1_crossbow, "khazad1_crossbow");
		register(khazad2_battleaxe, "khazad2_battleaxe");
		register(khazad2_crossbow, "khazad2_crossbow");
		register(khazad2_dagger, "khazad2_dagger");
		register(khazad2_dagger_poisoned, "khazad2_dagger_poisoned");
		register(khazad2_hammer, "khazad2_hammer");
		register(khazad2_pike, "khazad2_pike");
		register(khazad2_spear, "khazad2_spear");
		register(khazad2_sword, "khazad2_sword");
		register(khazady_crossbow, "khazady_crossbow");
		register(mordor2_polearm, "mordor2_polearm");
		register(mordory_spear, "mordory_spear");
		register(nandor1_pike, "nandor1_pike");
		register(nandor2_bow, "nandor2_bow");
		register(nandor2_dagger, "nandor2_dagger");
		register(nandor2_dagger_poisoned, "nandor2_dagger_poisoned");
		register(nandor2_pike, "nandor2_pike");
		register(nandor2_polearm, "nandor2_polearm");
		register(nandor2_spear, "nandor2_spear");
		register(nandor2_sword, "nandor2_sword");
		register(nandory_bow, "nandory_bow");
		register(noldor1_pike, "noldor1_pike");
		register(noldor2_bow, "noldor2_bow");
		register(noldor2_dagger, "noldor2_dagger");
		register(noldor2_dagger_poisoned, "noldor2_dagger_poisoned");
		register(noldor2_pike, "noldor2_pike");
		register(noldor2_polearm, "noldor2_polearm");
		register(noldor2_spear, "noldor2_spear");
		register(noldor2_sword, "noldor2_sword");
		register(noldory_sword, "noldory_sword");
		register(north2_bow, "north2_bow");
		register(north2_dagger, "north2_dagger");
		register(north2_dagger_poisoned, "north2_dagger_poisoned");
		register(north2_hammer, "north2_hammer");
		register(north2_pike, "north2_pike");
		register(north2_spear, "north2_spear");
		register(north2_sword, "north2_sword");
		register(northy_sword, "northy_sword");
		register(numenor1_battleaxe, "numenor1_battleaxe");
		register(numenor1_crossbow, "numenor1_crossbow");
		register(numenor2_battleaxe, "numenor2_battleaxe");
		register(numenor2_bow, "numenor2_bow");
		register(numenor2_crossbow, "numenor2_crossbow");
		register(numenor2_dagger, "numenor2_dagger");
		register(numenor2_dagger_poisoned, "numenor2_dagger_poisoned");
		register(numenor2_hammer, "numenor2_hammer");
		register(numenor2_pike, "numenor2_pike");
		register(numenor2_spear, "numenor2_spear");
		register(numenor2_sword, "numenor2_sword");
		register(numenory_spear, "numenory_spear");
		register(red_dwarven1_crossbow, "red_dwarven1_crossbow");
		register(red_dwarven2_crossbow, "red_dwarven2_crossbow");
		register(red_dwarven2_dagger, "red_dwarven2_dagger");
		register(red_dwarven2_dagger_poisoned, "red_dwarven2_dagger_poisoned");
		register(red_dwarven2_hammer, "red_dwarven2_hammer");
		register(red_dwarven2_pike, "red_dwarven2_pike");
		register(red_dwarven2_spear, "red_dwarven2_spear");
		register(red_dwarven2_sword, "red_dwarven2_sword");
		register(red_dwarveny_crossbow, "red_dwarveny_crossbow");
		register(rhovanion2_battleaxe, "rhovanion2_battleaxe");
		register(rhovanion2_bow, "rhovanion2_bow");
		register(rhovanion2_dagger, "rhovanion2_dagger");
		register(rhovanion2_dagger_poisoned, "rhovanion2_dagger_poisoned");
		register(rhovanion2_pike, "rhovanion2_pike");
		register(rhovanion2_spear, "rhovanion2_spear");
		register(rhovanion2_sword, "rhovanion2_sword");
		register(rhovaniony_sword, "rhovaniony_sword");
		register(rhun2_bow, "rhun2_bow");
		register(rhun2_dagger, "rhun2_dagger");
		register(rhun2_dagger_poisoned, "rhun2_dagger_poisoned");
		register(rhun2_pike, "rhun2_pike");
		register(rhun2_spear, "rhun2_spear");
		register(rhun2_sword, "rhun2_sword");
		register(rhuny_pike, "rhuny_pike");
		register(sindar1_pike, "sindar1_pike");
		register(sindar2_bow, "sindar2_bow");
		register(sindar2_dagger, "sindar2_dagger");
		register(sindar2_dagger_poisoned, "sindar2_dagger_poisoned");
		register(sindar2_pike, "sindar2_pike");
		register(sindar2_polearm, "sindar2_polearm");
		register(sindar2_spear, "sindar2_spear");
		register(sindar2_sword, "sindar2_sword");
		register(sindary_pike, "sindary_pike");
		register(standart1_bow, "standart1_bow");
		register(standart1_crossbow, "standart1_crossbow");
		register(standart2_bow, "standart2_bow");
		register(standart2_crossbow, "standart2_crossbow");
		register(jabroni, "jabroni");
		register(darkgrove_bow, "darkgrove_bow");
		register(darkgrove_pike, "darkgrove_pike");
		register(darkgrove_sword, "darkgrove_sword");
		register(guardian_crossbow, "guardian_crossbow");
		register(guardian_dagger_poisoned, "guardian_dagger_poisoned");
		register(guardian_spear, "guardian_spear");
		register(dark_bow, "dark_bow");
		register(dark_crossbow, "dark_crossbow");
		register(dark_spear, "dark_spear");
		register(dark_sword, "dark_sword");
		register(light_bow, "light_bow");
		register(light_crossbow, "light_crossbow");
		register(light_spear, "light_spear");
		register(light_sword, "light_sword");
		register(ultraviolet_sword, "ultraviolet_sword");
		register(ultraviolet_battleaxe, "ultraviolet_battleaxe");
		register(arrow_hunger, "arrow_hunger");
		register(arrow_blindness, "arrow_blindness");
		register(arrow_slowness, "arrow_slowness");
		register(crossbow_bolt_hunger, "crossbow_bolt_hunger");
		register(crossbow_bolt_blindness, "crossbow_bolt_blindness");
		register(crossbow_bolt_slowness, "crossbow_bolt_slowness");
		register(crossbow_bolt_fire, "crossbow_bolt_fire");
		register(arrow_fire, "arrow_fire");

		register(apple_cookies, "apple_cookies");
		register(berry_cookies, "berry_cookies");
		register(bottle1, "bottle1");
		register(bottle2, "bottle2");
		register(bottle3, "bottle3");
		register(chocolate_cookies, "chocolate_cookies");
		register(fish_arapaima, "fish_arapaima");
		register(fish_atlantic_cod, "fish_atlantic_cod");
		register(fish_atlantic_halibut, "fish_atlantic_halibut");
		register(fish_atlantic_herring, "fish_atlantic_herring");
		register(fish_bayad, "fish_bayad");
		register(fish_blackfish, "fish_blackfish");
		register(fish_bluegill, "fish_bluegill");
		register(fish_boulti, "fish_boulti");
		register(fish_brown_shrooma, "fish_brown_shrooma");
		register(fish_brown_trout, "fish_brown_trout");
		register(fish_capitaine, "fish_capitaine");
		register(fish_carp, "fish_carp");
		register(fish_catfish, "fish_catfish");
		register(fish_fish_bones, "fish_fish_bones");
		register(fish_goldfish, "fish_goldfish");
		register(fish_minnow, "fish_minnow");
		register(fish_muskellunge, "fish_muskellunge");
		register(fish_pacific_halibut, "fish_pacific_halibut");
		register(fish_perch, "fish_perch");
		register(fish_pink_salmon, "fish_pink_salmon");
		register(fish_piranha, "fish_piranha");
		register(fish_pollock, "fish_pollock");
		register(fish_rainbow_trout, "fish_rainbow_trout");
		register(fish_red_grouper, "fish_red_grouper");
		register(fish_red_shrooma, "fish_red_shrooma");
		register(fish_smallmouth_bass, "fish_smallmouth_bass");
		register(fish_synodontis, "fish_synodontis");
		register(fish_tambaqui, "fish_tambaqui");
		register(fish_tuna, "fish_tuna");
		register(grapefruit, "grapefruit");
		register(heal1, "heal1");
		register(heal2, "heal2");
		register(heal3, "heal3");
		register(honey_cookies, "honey_cookies");
		register(kiwi, "kiwi");
		register(maple_leaf, "maple_leaf");
		register(milk_cookies, "milk_cookies");
		register(pineapple, "pineapple");
		register(raspberry, "raspberry");
		register(rhubarb_pie, "rhubarb_pie");
		register(treasure_chest, "treasure_chest");
		register(watermelon_cookies, "watermelon_cookies");
	}

	private static void register(Item item, String name) {
		String lowerUnderscoreName = CaseFormat.LOWER_CAMEL.to(CaseFormat.LOWER_UNDERSCORE, name);
		item.setUnlocalizedName(lowerUnderscoreName);
		item.setTextureName("bd:" + lowerUnderscoreName);
		GameRegistry.registerItem(item, lowerUnderscoreName);
	}

	public static void registerBlock(Block block, String name) {
		String lowerUnderscoreName = CaseFormat.LOWER_CAMEL.to(CaseFormat.LOWER_UNDERSCORE, name);
		block.setBlockName(lowerUnderscoreName);
		block.setBlockTextureName("bd:" + lowerUnderscoreName);
		GameRegistry.registerBlock(block, lowerUnderscoreName);
	}

	public static void registerItemLotr(Item item, String name) {
		String lowerUnderscoreName = CaseFormat.LOWER_CAMEL.to(CaseFormat.LOWER_UNDERSCORE, name);
		item.setUnlocalizedName(lowerUnderscoreName);
		item.setTextureName("lotr:" + lowerUnderscoreName);
		GameRegistry.registerItem(item, lowerUnderscoreName);
	}
}