package bd.database;

import lotr.common.LOTRMod;
import lotr.common.entity.npc.*;
import lotr.common.entity.npc.LOTRTradeEntries.TradeType;
import net.minecraft.init.*;
import net.minecraft.item.ItemStack;

public class BDTradeEntries {
	public static LOTRTradeEntries EREGION_SMITH_BUY;
	public static LOTRTradeEntries KHAND_BLACKSMITH_BUY;
	public static LOTRTradeEntries KHAND_MASON_BUY;
	public static LOTRTradeEntries KHAND_GOLDSMITH_BUY;

	static {
		EREGION_SMITH_BUY = new LOTRTradeEntries(TradeType.BUY, new LOTRTradeEntry(new ItemStack(BDRegistry.table_eregion), 100), new LOTRTradeEntry(new ItemStack(BDRegistry.eregion1_sword), 18), new LOTRTradeEntry(new ItemStack(BDRegistry.eregion1_dagger), 14), new LOTRTradeEntry(new ItemStack(BDRegistry.eregion1_spear), 18), new LOTRTradeEntry(new ItemStack(BDRegistry.eregion1_polearm), 18), new LOTRTradeEntry(new ItemStack(LOTRMod.axeElven), 15), new LOTRTradeEntry(new ItemStack(LOTRMod.pickaxeElven), 15), new LOTRTradeEntry(new ItemStack(LOTRMod.shovelElven), 12), new LOTRTradeEntry(new ItemStack(BDRegistry.eregion1_helmet), 18), new LOTRTradeEntry(new ItemStack(BDRegistry.eregion1_chestplate), 25), new LOTRTradeEntry(new ItemStack(BDRegistry.eregion1_leggings), 22), new LOTRTradeEntry(new ItemStack(BDRegistry.eregion1_boots), 16), new LOTRTradeEntry(new ItemStack(BDRegistry.eregion1_bow), 20), new LOTRTradeEntry(new ItemStack(Items.arrow, 4), 3));
		KHAND_BLACKSMITH_BUY = new LOTRTradeEntries(TradeType.BUY, new LOTRTradeEntry(new ItemStack(BDRegistry.table_khand), 100), new LOTRTradeEntry(new ItemStack(BDRegistry.khand1_sword), 15), new LOTRTradeEntry(new ItemStack(BDRegistry.khand1_dagger), 9), new LOTRTradeEntry(new ItemStack(BDRegistry.khand1_pike), 16), new LOTRTradeEntry(new ItemStack(BDRegistry.khand1_spear), 16), new LOTRTradeEntry(new ItemStack(BDRegistry.khand1_hammer), 18), new LOTRTradeEntry(new ItemStack(BDRegistry.khand1_chestplate), 32), new LOTRTradeEntry(new ItemStack(BDRegistry.khand1_leggings), 26), new LOTRTradeEntry(new ItemStack(BDRegistry.khand1_boots), 17), new LOTRTradeEntry(new ItemStack(BDRegistry.khand2_helmet), 30), new LOTRTradeEntry(new ItemStack(BDRegistry.khand2_chestplate), 45), new LOTRTradeEntry(new ItemStack(BDRegistry.khand2_leggings), 35), new LOTRTradeEntry(new ItemStack(BDRegistry.khand2_boots), 25), new LOTRTradeEntry(new ItemStack(LOTRMod.blacksmithHammer), 18), new LOTRTradeEntry(new ItemStack(Blocks.iron_bars, 8), 20), new LOTRTradeEntry(new ItemStack(LOTRMod.bronzeBars, 8), 20), new LOTRTradeEntry(new ItemStack(LOTRMod.crossbowBolt, 4), 3), new LOTRTradeEntry(new ItemStack(LOTRMod.ironCrossbow), 15), new LOTRTradeEntry(new ItemStack(LOTRMod.bronzeCrossbow), 12));
		KHAND_MASON_BUY = new LOTRTradeEntries(TradeType.BUY, new LOTRTradeEntry(new ItemStack(BDRegistry.table_khand), 100), new LOTRTradeEntry(new ItemStack(Blocks.stone, 8), 2), new LOTRTradeEntry(new ItemStack(Blocks.cobblestone, 8), 1), new LOTRTradeEntry(new ItemStack(Blocks.stonebrick, 8, 0), 2), new LOTRTradeEntry(new ItemStack(LOTRMod.brick5, 8, 11), 3), new LOTRTradeEntry(new ItemStack(LOTRMod.brick5, 1, 12), 2), new LOTRTradeEntry(new ItemStack(LOTRMod.brick5, 1, 15), 2), new LOTRTradeEntry(new ItemStack(LOTRMod.brick6, 1, 0), 2), new LOTRTradeEntry(new ItemStack(LOTRMod.pillar2, 4, 8), 3), new LOTRTradeEntry(new ItemStack(LOTRMod.rock, 8, 4), 8), new LOTRTradeEntry(new ItemStack(LOTRMod.brick6, 8, 1), 8), new LOTRTradeEntry(new ItemStack(LOTRMod.brick6, 1, 2), 8), new LOTRTradeEntry(new ItemStack(LOTRMod.pillar2, 4, 9), 8), new LOTRTradeEntry(new ItemStack(Blocks.hardened_clay, 8), 4), new LOTRTradeEntry(new ItemStack(Blocks.sandstone, 8), 4), new LOTRTradeEntry(new ItemStack(LOTRMod.redSandstone, 8), 12), new LOTRTradeEntry(new ItemStack(LOTRMod.whiteSandstone, 8), 6));
		KHAND_GOLDSMITH_BUY = new LOTRTradeEntries(TradeType.BUY, new LOTRTradeEntry(new ItemStack(LOTRMod.goldRing), 15), new LOTRTradeEntry(new ItemStack(LOTRMod.silverRing), 12), new LOTRTradeEntry(new ItemStack(LOTRMod.gobletGold), 27), new LOTRTradeEntry(new ItemStack(LOTRMod.gobletSilver), 18), new LOTRTradeEntry(new ItemStack(LOTRMod.gobletCopper), 8), new LOTRTradeEntry(new ItemStack(LOTRMod.chandelier, 1, 3), 15), new LOTRTradeEntry(new ItemStack(LOTRMod.chandelier, 1, 2), 12), new LOTRTradeEntry(new ItemStack(LOTRMod.birdCage, 1, 3), 20), new LOTRTradeEntry(new ItemStack(LOTRMod.birdCage, 1, 2), 15), new LOTRTradeEntry(new ItemStack(LOTRMod.goldBars), 8), new LOTRTradeEntry(new ItemStack(LOTRMod.silverBars), 6), new LOTRTradeEntry(new ItemStack(LOTRMod.brick6, 1, 0), 3), new LOTRTradeEntry(new ItemStack(BDRegistry.khand2_helmet), 30), new LOTRTradeEntry(new ItemStack(BDRegistry.khand2_chestplate), 45), new LOTRTradeEntry(new ItemStack(BDRegistry.khand2_leggings), 35), new LOTRTradeEntry(new ItemStack(BDRegistry.khand2_boots), 25));
	}
}